FROM python:3.11-slim

RUN mkdir /app 

COPY  /web_api /app
COPY pyproject.toml /app
COPY poetry.lock /app

WORKDIR /app/
ENV PYTHONPATH=${PYTHONPATH}:${PWD}

RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
