FROM python:3.11

WORKDIR /code

RUN pip install poetry

COPY pyproject.toml poetry.lock /code/

RUN poetry install && rm -rf $POETRY_CACHE_DIR

COPY ./web_api /code/app

CMD ["fastapi", "run", "app/main.py", "--port", "80"]